import { z } from 'zod';
export declare const EnvSchema: z.ZodObject<{
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    JWT_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    LITELLM_BASE_URL: z.ZodOptional<z.ZodString>;
    LITELLM_MASTER_KEY: z.ZodOptional<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodOptional<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_PUBLIC_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_SECRET_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_HOST: z.ZodOptional<z.ZodString>;
    QUEUE_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    PORT: z.ZodDefault<z.ZodString>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
}, "strip", z.ZodTypeAny, {
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    QUEUE_ENABLED: boolean;
    PORT: string;
    NODE_ENV: "development" | "production" | "test";
    LITELLM_BASE_URL?: string | undefined;
    LITELLM_MASTER_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    LANGFUSE_PUBLIC_KEY?: string | undefined;
    LANGFUSE_SECRET_KEY?: string | undefined;
    LANGFUSE_HOST?: string | undefined;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    LITELLM_BASE_URL?: string | undefined;
    LITELLM_MASTER_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    LANGFUSE_PUBLIC_KEY?: string | undefined;
    LANGFUSE_SECRET_KEY?: string | undefined;
    LANGFUSE_HOST?: string | undefined;
    QUEUE_ENABLED?: string | undefined;
    PORT?: string | undefined;
    NODE_ENV?: "development" | "production" | "test" | undefined;
}>;
export type Env = z.infer<typeof EnvSchema>;
